export const OPEN_ADD_NEW_LOG_DIALOG = 'OPEN_ADD_NEW_LOG_DIALOG';
export const CLOSE_ADD_NEW_LOG_DIALOG = 'CLOSE_ADD_NEW_LOG_DIALOG';

export const FETCH_LOGS_REQUEST = 'FETCH_LOGS_REQUEST';
export const FETCH_LOGS_FAILURE = 'FETCH_LOGS_FAILURE';
export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS';

export const FETCH_RECORDING_STATUS_REQUEST = 'FETCH_RECORDING_STATUS_REQUEST';
export const FETCH_RECORDING_STATUS_FAILURE = 'FETCH_RECORDING_STATUS_FAILURE';
export const FETCH_RECORDING_STATUS_SUCCESS = 'FETCH_RECORDING_STATUS_SUCCESS';

export const INSERT_OR_UPDATE_LOG_REQUEST = 'INSERT_OR_UPDATE_LOG_REQUEST';
export const INSERT_OR_UPDATE_LOG_FAILURE = 'INSERT_OR_UPDATE_LOG_FAILURE';
export const INSERT_OR_UPDATE_LOG_SUCCESS = 'INSERT_OR_UPDATE_LOG_SUCCESS';

export const DELETE_LOG_REQUEST = 'DELETE_LOG_REQUEST';
export const DELETE_LOG_FAILURE = 'DELETE_LOG_FAILURE';
export const DELETE_LOG_SUCCESS = 'DELETE_LOG_SUCCESS';

export const DOWNLOAD_LOG_FILE_REQUEST = 'DOWNLOAD_LOG_FILE_REQUEST';
export const DOWNLOAD_LOG_FILE_FAILURE = 'DOWNLOAD_LOG_FILE_FAILURE';
export const DOWNLOAD_LOG_FILE_SUCCESS = 'DOWNLOAD_LOG_FILE_SUCCESS';

export const START_RECORDING_REQUEST = 'START_RECORDING_REQUEST';
export const START_RECORDING_FAILURE = 'START_RECORDING_FAILURE';
export const START_RECORDING_SUCCESS = 'START_RECORDING_SUCCESS';