export const OPEN_ADD_NEW_LOG_DIALOG = 'OPEN_ADD_NEW_LOG_DIALOG';
export const CLOSE_ADD_NEW_LOG_DIALOG = 'CLOSE_ADD_NEW_LOG_DIALOG';

export const FETCH_LOGS_REQUEST = 'FETCH_LOGS_REQUEST';
export const FETCH_LOGS_FAILURE = 'FETCH_LOGS_FAILURE';
export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS';

export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';

export const FETCH_RECORDING_STATUS_REQUEST = 'FETCH_RECORDING_STATUS_REQUEST';
export const FETCH_RECORDING_STATUS_FAILURE = 'FETCH_RECORDING_STATUS_FAILURE';
export const FETCH_RECORDING_STATUS_SUCCESS = 'FETCH_RECORDING_STATUS_SUCCESS';

export const ADD_NEW_LOG = 'ADD_NEW_LOG';
