export const OPEN_ADD_NEW_LOG_DIALOG = 'OPEN_ADD_NEW_LOG_DIALOG';
export const CLOSE_ADD_NEW_LOG_DIALOG = 'CLOSE_ADD_NEW_LOG_DIALOG';
export const ADD_NEW_LOG = 'ADD_NEW_LOG';
export const FETCH_LOGS_REQUEST = 'FETCH_LOGS_REQUEST';
export const FETCH_LOGS_FAILURE = 'FETCH_LOGS_FAILURE';
export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS';